gpt:
  api-key: ${GPT_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsprompt
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect