spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsprompt-test
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    user: root
    password: root
    baseline-on-migrate: true
    enabled: true